--liquibase formatted sql
--changeset TPE:1
CREATE TABLE UTILISATEUR (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    MAXIMUM_BENCH INTEGER,
    MAXIMUM_SQUAT INTEGER,
    MAXIMUM_DEADLIFT INTEGER,
);

--liquibase formatted sql
--changeset TPE:2
INSERT INTO UTILISATEUR VALUES(1,'Aria', 'Stark', 100,120,150);
INSERT INTO UTILISATEUR VALUES(2,'Ned', 'Stark', 120,160,200);
